### PR TITLE
a less intrusive way to tune the amount of debug info

### PR DESCRIPTION
**Pull request by ensonic**
Suggest to use systemctl set-environment and systemctl unset-environmen to tweak G_MESSAGES_DEBUG.

### CODE REVIEW

**Comment by dlech** [comment]
I have a couple questions about `sudo systemctl set-environment G_MESSAGES_DEBUG=all`.
1. Wouldn't this affect _all_ systemd services?
2. Does it persist across reboots?

**Comment by ensonic** [comment]
I does not persist (it casues the init process to call setenv from libc). And yes, it affect everything started from systemd afterwards.

**Comment by dlech** [comment]
hmm... I think I like the .conf file better. Are there any compelling reasons we should be suggesting to do it this way instead?

**Comment by ensonic** [comment]
I can also keep the previous and just add the alternative suggestion. I like the non-conf version better since one cannot forget to deactivate it :)

**Comment by dlech** [comment]
Alright, you talked me into it. :wink:

**Pull request merged**
