### PR TITLE
openroberta: focus on the previously selected 'connect' button

### PR DESCRIPTION
**Pull request by ensonic**
This feature was lost with the previous refactorings.

### CODE REVIEW

**Comment by ensonic** [comment]
Something broken my brickstrap setup - so I only tried this on the desktop so far. I guess the image I was working on is getting too old. Will keep trying to figure how this is supposed to be updated. I usually take notes of everything, but this time I apparently did not write how how I created it :/ and the README in brickstrap does not tell either,

**Comment by dlech** [comment]
Looks good to me.

If you are using brickstrap from git, then things have changed significantly. Use the packaged version or latest git tag for the time being.

**Comment by ensonic** [comment]
I've now got the builds to work again. The main trouble with this is that it is not scrolling to the select sever when initially showing the window. Will debug a bit more.

**Comment by ensonic** [comment]
Should be good now. See also: https://github.com/ev3dev/ev3devKit/pull/4

**Comment by dlech** [comment]
By "good now" do you mean "tested, working and ready to merge"?

**Comment by ensonic** [comment]
Yep, tested on the ev3 and works.

**Comment by dlech** [comment]
Thanks!

**Pull request merged**
